import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Check, ShieldCheck, LockKeyhole, Users, Flag, FileCheck2, ScanLine, CircleCheck, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { type Campaign, compactMoney, protocolSteps } from '@/lib/demo-data';
export function Badge({children,tone='success'}:{children:ReactNode;tone?:'success'|'warning'|'muted'}){return <span className={`badge ${tone==='warning'?'badge-warning':tone==='muted'?'badge-muted':''}`}>{tone==='success'&&<ShieldCheck/>}{children}</span>}
export function Progress({value}:{value:number}){return <div className="progress" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><span className="progress-filled" ref={node=>{if(node)node.style.flex=String(value)}}/><span className="progress-rest" ref={node=>{if(node)node.style.flex=String(100-value)}}/></div>}
export function Reveal({children,className=''}:{children:ReactNode;className?:string}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){node.classList.add('visible');observer.unobserve(node)}})},{threshold:.1});observer.observe(node);return()=>observer.disconnect()},[]);return <div ref={ref} className={`reveal ${className}`}>{children}</div>}
export function Count({value,prefix='',suffix=''}:{value:number;prefix?:string;suffix?:string}){const [shown,setShown]=useState(value);const ref=useRef<HTMLSpanElement>(null);useEffect(()=>{const node=ref.current;if(!node||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const observer=new IntersectionObserver(entries=>{if(!entries[0]?.isIntersecting)return;observer.disconnect();const start=performance.now();let id=0;const frame=(t:number)=>{const p=Math.min((t-start)/1200,1);setShown(value*(1-Math.pow(1-p,3)));if(p<1)id=requestAnimationFrame(frame)};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id)});observer.observe(node);return()=>observer.disconnect()},[value]);return <span ref={ref}>{prefix}{Number.isInteger(value)?Math.round(shown).toLocaleString('en-IN'):shown.toFixed(1)}{suffix}</span>}
const flowIcons=[Users,LockKeyhole,Flag,FileCheck2,ScanLine,ShieldCheck,CircleCheck];
export function FundFlow(){return <div className="flow-line">{protocolSteps.map((s,i)=>{const Icon=flowIcons[i]??Flag;return <div className="contents" key={s}><div className="flow-step"><span className="flow-icon"><Icon/></span><span className={i===6?'flow-end':''}>{s}</span></div>{i<6&&<span className="flow-connector" aria-hidden="true"/>}</div>})}</div>}
export function CampaignCard({campaign:c}:{campaign:Campaign}){const pct=Math.round(c.raised/c.goal*100);return <article className="campaign-card"><Link to="/campaign/$id" params={{id:c.id}}><div className="campaign-media"><img src={c.image} alt={c.title} width={1024} height={640} loading="lazy"/><Badge tone={c.status==='Verified'?'success':'warning'}>{c.status==='Verified'?'Milestone verified':'Verification in review'}</Badge></div></Link><div className="campaign-body"><div className="card-category">{c.category}</div><Link to="/campaign/$id" params={{id:c.id}}><h3>{c.title}</h3></Link><p>{c.description}</p><div className="mt-2 text-[10px] text-muted-foreground">By {c.creator}</div><div className="campaign-funding"><div><strong>{compactMoney(c.raised)}</strong> <span>/ {compactMoney(c.goal)}</span></div><span>{pct}%</span></div><Progress value={pct}/><div className="campaign-meta"><span>{c.verified} / {c.total} milestones verified</span><span title={c.deadline}>{c.days} days left</span></div><div className="mt-3 text-[10px] text-muted-foreground">Current: {c.current}</div><div className="campaign-bottom"><span className="flex items-center gap-1"><Check/>Creator stake deposited</span><Button asChild variant="ghost" size="icon" title="View campaign"><Link to="/campaign/$id" params={{id:c.id}} aria-label={`View ${c.title}`}><ArrowUpRight/></Link></Button></div></div></article>}
export function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:ReactNode}){return <div className="page-top"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p className="section-description">{description}</p>}</div>{action}</div>}
export function SectionHeading({eyebrow,title,children}:{eyebrow:string;title:string;children?:ReactNode}){return <div className="section-header"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{children}</div>}
export function Row({label,children}:{label:string;children:ReactNode}){return <div className="row"><span>{label}</span><span>{children}</span></div>}
export function Stats({items,dashboard=false}:{items:{label:string;value:string|ReactNode;sub?:string}[];dashboard?:boolean}){return <div className={dashboard?'dashboard-stats':'stats-grid'}>{items.map(s=><div className="stat" key={s.label}><div className="stat-value">{s.value}</div><div className="stat-label">{s.label}</div>{s.sub&&<div className="stat-sub">{s.sub}</div>}</div>)}</div>}
export function Empty({children}:{children:ReactNode}){return <div className="empty">{children}</div>}
export { ArrowRight };
