import { createContext, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, Wallet, X, Menu, LayoutDashboard, Compass, FolderOpen, FileCheck2, Receipt, RotateCcw, Settings, UserRound, Plus, Building2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { BrandMark } from './brand';
const AppContext=createContext({wallet:false,connect:()=>{},notify:(_message:string)=>{}});
export const useApp=()=>useContext(AppContext);
export function AppShell({children}:{children:ReactNode}){const [wallet,setWallet]=useState(false);const [modal,setModal]=useState(false);const [menu,setMenu]=useState(false);const [notice,setNotice]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);useEffect(()=>()=>clearTimeout(timer.current),[]);const notify=(message:string)=>{setNotice(message);clearTimeout(timer.current);timer.current=setTimeout(()=>setNotice(''),4500)};return <AppContext.Provider value={{wallet,connect:()=>setModal(true),notify}}><header className="site-header"><div className="container header-inner"><Link to="/" className="brand"><BrandMark/>ProofFund<span className="text-primary">.</span></Link><nav className="nav" aria-label="Main navigation"><Link to="/explore">Explore</Link><Link to="/how-it-works">How It Works</Link><Link to="/verify">Verify Proof</Link><Link to="/dashboard/organization">For Organizations</Link></nav><div className="header-actions"><span className="demo-indicator">Demo environment</span><Button className="wallet-button" variant="outline" onClick={()=>wallet?setWallet(false):setModal(true)}><Wallet/>{wallet?'Demo wallet':'Connect Wallet'}</Button><Button className="mobile-toggle" variant="ghost" size="icon" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div></div>{menu&&<nav className="mobile-nav" onClick={()=>setMenu(false)}><Link to="/explore">Explore</Link><Link to="/how-it-works">How It Works</Link><Link to="/verify">Verify Proof</Link><Link to="/dashboard/organization">For Organizations</Link><Link to="/dashboard/donor">My dashboard</Link></nav>}</header>{children}<footer className="footer"><div className="container footer-inner"><Link to="/" className="brand"><BrandMark/>ProofFund<span className="text-primary">.</span></Link><p>© 2026 ProofFund. Trust, made verifiable.</p><div className="footer-links"><Link to="/about">About</Link><Link to="/how-it-works">The protocol</Link><Link to="/dashboard/donor">Dashboard</Link><Link to="/settings">Settings</Link></div></div></footer>{modal&&<Modal title="Connect your wallet" onClose={()=>setModal(false)}><p>Explore ProofFund with a demo wallet. No real wallet connection, signature, or funds are requested.</p><Button variant="outline" className="wallet-option" onClick={()=>{setWallet(true);setModal(false);notify('Demo wallet connected. No real wallet was accessed.')}}><Wallet/>Continue with demo wallet<ArrowRight/></Button></Modal>}{notice&&<div className="notification" role="status">{notice}</div>}</AppContext.Provider>}
export function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement;ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const focusables=ref.current?.querySelectorAll<HTMLElement>('button,input,a,select,textarea');const first=focusables?.[0],last=focusables?.[focusables.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);if(previous instanceof HTMLElement)previous.focus()}},[onClose]);return <div className="modal-overlay" onClick={onClose}><div className="modal" ref={ref} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} onClick={e=>e.stopPropagation()}><div className="modal-title"><h2>{title}</h2><Button size="icon" variant="ghost" aria-label="Close dialog" onClick={onClose}><X/></Button></div>{children}</div></div>}
export function Workspace({children}:{children:ReactNode}){return <div className="workspace"><aside className="sidebar"><p>Workspace</p><Link to="/dashboard/donor"><LayoutDashboard/>Donor overview</Link><Link to="/dashboard/creator"><FolderOpen/>Creator overview</Link><Link to="/dashboard/organization"><Building2/>Organization</Link><p>Funding</p><Link to="/explore"><Compass/>Explore campaigns</Link><Link to="/create"><Plus/>Create campaign</Link><Link to="/verify"><FileCheck2/>Verify proof</Link><Link to="/transactions"><Receipt/>Transactions</Link><Link to="/refunds"><RotateCcw/>Refunds</Link><p>Account</p><Link to="/profile"><UserRound/>Profile</Link><Link to="/settings"><Settings/>Settings</Link></aside><main className="workspace-main">{children}</main></div>}
